name = "carbon-emissions-counter"
compatibility_date = "2024-01-10"

[build]
command = "pip install -r requirements.txt"

[site]
bucket = "./static"
entry-point = "app"

[[routes]]
pattern = "/*"
script = "functions/_middleware.py"

[env.production]
name = "carbon-emissions-counter-prod"
