name = "carbon-emissions-counter"
compatibility_date = "2024-01-10"

[site]
bucket = "./static"

[build]
command = "cp -r templates/* static/"

[[redirects]]
pattern = "/"
destination = "/index.html"

[[redirects]]
pattern = "/*"
destination = "/index.html"
status = 200
